### ISSUE TITLE
Clicking a Documentation PDF seems to do nothing

### ISSUE THREAD

**Issue by asherao** [jeffboulanger/DCS-Alternative-Launcher#33] opened 2019-08-31 02:11 UTC
Version: 0.15.7177.42566
This applies for modules I own and modules I do not own.
(Having Chuck's Guide as a PDF may be a little misleading as it links to a browser webpage, not a .pdf)

**Comment by jeffboulanger** [comment] 2019-08-31 06:31
@asherao I cant reproduce, this works perfect for me on all modules. 

1.  It should only show you modules you have installed, please let me know if this is not the case. 
2.  Chucks guides are PDFs, they just happen to open in your browser.

Please attach trace.log if the issue continues

**Comment by asherao** [comment] 2019-08-31 09:09
[trace.log](https://github.com/jeffboulanger/DCS-Alternative-Launcher/files/3562254/trace.log)
Issue continues. Trace Log Attached. DAL Version: 0.15.7181.42496

**Comment by jeffboulanger** [comment] 2019-09-25 21:56
@asherao I believe this to be fixed now, please test and re-open if need be

**Closed by jeffboulanger** 2019-09-25 21:56 UTC
Labels: bug, question
